### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [slacka/WinUSBplus#100]
This is derived from issue #88 .

The original WinUSB is pretty much a complete software project (it even has a [Ubuntu PPA Repository](http://en.congelli.eu/prog_info_winusb.html#bin), which we currently not been able to have an official one) and while @Congelli501 not seems to continue maintaining their project it doesn't seem to be ethical to just "take over" name owned by other people.

The solution, is to change the project, package and application name, @slacka any ideas?

The following are some suggestions, I'm against using `winusb-reborn` and other names that implies the original project's status

**Comment by Lin-Buo-Ren** [comment]
WinUSB, the fork(winusb-the-fork)  
We can also modify the current logo and add and actual fork to it

**Comment by Lin-Buo-Ren** [comment]
winusb-slacka  
A trivial name.

**Comment by JonnyTech** [comment]
WinUsbCreator? WinUsbLinux? UsbWin (see what I did there?)?

**Comment by Lin-Buo-Ren** [comment]
WoeUSB
In GNU sense

**Comment by JonnyTech** [comment]
What made you think that I was not praising your project? USB-FTW! ;)

**Comment by slacka** [comment]
Yes, it's a good idea. I like WoeUSB but it doesn't the relation to WinUSB that a suffix would. How about 
WinUSB+ or WinUSB-2?

**Comment by Lin-Buo-Ren** [comment]
I'm slightly prefer WinUSB+ as -2 also implies the relationship with the original.

**Comment by Lin-Buo-Ren** [comment]
Also `winusb+` seems to be a valid package name, I probably would change the package name for now.

**Comment by Lin-Buo-Ren** [comment]
This issue is re-opened so that more consensus can be meet.

Another issue of `WinUSB` is that it clash with Windows generic WinUSB driver, this pretty much prevent users to reach this project from the search engine results

**Comment by slacka** [comment]
This repo is at top of a google search for me in USA for both WinUSB and WinUSB+. Not sure people will be searching for the project by name, more likely they will find this with a search like: "How to Make A Bootable Windows 10 USB Install Stick On Linux?" Not sure conflicting with a driver name is a big deal, but if you think a totally unique name is best, then I'm fine with `WoeUSB`.

**Comment by Lin-Buo-Ren** [comment]
Then I (selfishly) make the final decision of using the name `WoeUSB`, @slacka please rename the repo name again, I'll make the change in the source code, thanks!
