### ISSUE TITLE
Enable slacka/WinUSBplus on Travis CI

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [slacka/WinUSBplus#101]
@slacka , I'm preparing to incorporate Travis CI, please enable this repo. on <https://travis-ci.org>

**Comment by Lin-Buo-Ren** [comment]
Current build result on my fork: <https://travis-ci.org/Lin-Buo-Ren/WinUSB/builds/241896599>

**Comment by slacka** [comment]
Should be enabled now.

**Comment by Lin-Buo-Ren** [comment]
Thanks!
