### ISSUE TITLE
Rename repository name and URL

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [slacka/WinUSBplus#102]
Since the #100 is applied we probably should also rename the repository name(and so, also the URL), however this will certainly break third party packaging due to the URL change.

**Comment by slacka** [comment]
As far as I know that shouldn't be a major issue. If someone brings it up, I'll see about redirecting the old URL to the new one.

**Comment by Lin-Buo-Ren** [comment]
GitHub doesn't allow plus sign to be used as repository name, maybe `WinUSBplus`?

**Comment by Lin-Buo-Ren** [comment]
Should be done now :-)
